title: Mark T Wetzel
email: mark.wetzel@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Mark Wetzel is a user experience designer and business owner based in Chicago.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "heymarkwetzel.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  heymarkwetzel
timezone: America/Chicago
permalink: /:title/
markdown: kramdown

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-feed

exclude: [README.md, Gemfile, Gemfile.lock]
