title: Postikard
email: hello@postikard.com
description: > # this means to ignore newlines until "baseurl:"
  Postikard is an app that aims to connect people through digital postcards.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "postikard.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  heymarkwetzel
timezone: America/Chicago
permalink: /:title/
markdown: kramdown

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-feed

exclude: [README.md, Gemfile, Gemfile.lock]
